// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AdaptEntriesForWeb(arg1, arg2, arg3, arg4) {
  return window['go']['main']['GUIApp']['AdaptEntriesForWeb'](arg1, arg2, arg3, arg4);
}

export function AdaptTextStyleForWeb(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['GUIApp']['AdaptTextStyleForWeb'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function AddConst(arg1, arg2) {
  return window['go']['main']['GUIApp']['AddConst'](arg1, arg2);
}

export function AddFont(arg1) {
  return window['go']['main']['GUIApp']['AddFont'](arg1);
}

export function AddPage(arg1, arg2, arg3) {
  return window['go']['main']['GUIApp']['AddPage'](arg1, arg2, arg3);
}

export function AddTextBlock(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['GUIApp']['AddTextBlock'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function BeginEdit() {
  return window['go']['main']['GUIApp']['BeginEdit']();
}

export function CompileDocumentHTML() {
  return window['go']['main']['GUIApp']['CompileDocumentHTML']();
}

export function CompilePageHTML(arg1) {
  return window['go']['main']['GUIApp']['CompilePageHTML'](arg1);
}

export function CompilePageHTMLFromDocument(arg1, arg2) {
  return window['go']['main']['GUIApp']['CompilePageHTMLFromDocument'](arg1, arg2);
}

export function CompilePageSVG(arg1) {
  return window['go']['main']['GUIApp']['CompilePageSVG'](arg1);
}

export function CompilePageSVGFromDocument(arg1, arg2) {
  return window['go']['main']['GUIApp']['CompilePageSVGFromDocument'](arg1, arg2);
}

export function EndEdit() {
  return window['go']['main']['GUIApp']['EndEdit']();
}

export function ExportHTMLFromDocument(arg1, arg2, arg3) {
  return window['go']['main']['GUIApp']['ExportHTMLFromDocument'](arg1, arg2, arg3);
}

export function ExportSVG(arg1) {
  return window['go']['main']['GUIApp']['ExportSVG'](arg1);
}

export function ExportSVGFromDocument(arg1) {
  return window['go']['main']['GUIApp']['ExportSVGFromDocument'](arg1);
}

export function FormatDocumentJSON(arg1) {
  return window['go']['main']['GUIApp']['FormatDocumentJSON'](arg1);
}

export function FormatPageDocumentJSON(arg1, arg2) {
  return window['go']['main']['GUIApp']['FormatPageDocumentJSON'](arg1, arg2);
}

export function GetAssetDataURI(arg1) {
  return window['go']['main']['GUIApp']['GetAssetDataURI'](arg1);
}

export function GetDocumentJSON() {
  return window['go']['main']['GUIApp']['GetDocumentJSON']();
}

export function GetDocumentPSRT() {
  return window['go']['main']['GUIApp']['GetDocumentPSRT']();
}

export function GetState() {
  return window['go']['main']['GUIApp']['GetState']();
}

export function MergePageDocumentPSRT(arg1, arg2, arg3) {
  return window['go']['main']['GUIApp']['MergePageDocumentPSRT'](arg1, arg2, arg3);
}

export function MovePage(arg1, arg2, arg3) {
  return window['go']['main']['GUIApp']['MovePage'](arg1, arg2, arg3);
}

export function OpenFileDialog() {
  return window['go']['main']['GUIApp']['OpenFileDialog']();
}

export function OpenImageFileDialog() {
  return window['go']['main']['GUIApp']['OpenImageFileDialog']();
}

export function ParseDocumentPSRT(arg1) {
  return window['go']['main']['GUIApp']['ParseDocumentPSRT'](arg1);
}

export function PatchMask(arg1, arg2, arg3) {
  return window['go']['main']['GUIApp']['PatchMask'](arg1, arg2, arg3);
}

export function PatchPage(arg1) {
  return window['go']['main']['GUIApp']['PatchPage'](arg1);
}

export function PatchText(arg1, arg2, arg3) {
  return window['go']['main']['GUIApp']['PatchText'](arg1, arg2, arg3);
}

export function Redo() {
  return window['go']['main']['GUIApp']['Redo']();
}

export function RefreshAssetURL(arg1) {
  return window['go']['main']['GUIApp']['RefreshAssetURL'](arg1);
}

export function RefreshPageImage() {
  return window['go']['main']['GUIApp']['RefreshPageImage']();
}

export function RemoveConst(arg1) {
  return window['go']['main']['GUIApp']['RemoveConst'](arg1);
}

export function RemoveFont(arg1) {
  return window['go']['main']['GUIApp']['RemoveFont'](arg1);
}

export function RemovePage(arg1) {
  return window['go']['main']['GUIApp']['RemovePage'](arg1);
}

export function RemoveText(arg1) {
  return window['go']['main']['GUIApp']['RemoveText'](arg1);
}

export function RenderTextContentHTML(arg1) {
  return window['go']['main']['GUIApp']['RenderTextContentHTML'](arg1);
}

export function ReorderText(arg1, arg2, arg3) {
  return window['go']['main']['GUIApp']['ReorderText'](arg1, arg2, arg3);
}

export function ReportClientError(arg1, arg2, arg3) {
  return window['go']['main']['GUIApp']['ReportClientError'](arg1, arg2, arg3);
}

export function Save() {
  return window['go']['main']['GUIApp']['Save']();
}

export function SaveAsDocumentJSON(arg1) {
  return window['go']['main']['GUIApp']['SaveAsDocumentJSON'](arg1);
}

export function SaveDocumentJSON(arg1) {
  return window['go']['main']['GUIApp']['SaveDocumentJSON'](arg1);
}

export function SelectText(arg1) {
  return window['go']['main']['GUIApp']['SelectText'](arg1);
}

export function SetActivePage(arg1) {
  return window['go']['main']['GUIApp']['SetActivePage'](arg1);
}

export function SetAutoCompile(arg1) {
  return window['go']['main']['GUIApp']['SetAutoCompile'](arg1);
}

export function SetDocumentFromPSRT(arg1) {
  return window['go']['main']['GUIApp']['SetDocumentFromPSRT'](arg1);
}

export function Undo() {
  return window['go']['main']['GUIApp']['Undo']();
}
