// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {styleadapter} from '../models';
import {main} from '../models';
import {visualapp} from '../models';

export function AdaptEntriesForWeb(arg1:string,arg2:number,arg3:number,arg4:number):Promise<Array<styleadapter.WebPreviewStyle>>;

export function AdaptTextStyleForWeb(arg1:string,arg2:string,arg3:number,arg4:number,arg5:number,arg6:number,arg7:number,arg8:number,arg9:number):Promise<styleadapter.WebPreviewStyle>;

export function AddConst(arg1:string,arg2:string):Promise<void>;

export function AddFont(arg1:string):Promise<void>;

export function AddPage(arg1:string,arg2:string,arg3:string):Promise<void>;

export function AddTextBlock(arg1:number,arg2:number,arg3:number,arg4:number,arg5:number,arg6:string,arg7:string,arg8:string):Promise<void>;

export function BeginEdit():Promise<void>;

export function CompileDocumentHTML():Promise<string>;

export function CompilePageHTML(arg1:string):Promise<string>;

export function CompilePageHTMLFromDocument(arg1:string,arg2:string):Promise<string>;

export function CompilePageSVG(arg1:string):Promise<main.CompileSVGResult>;

export function CompilePageSVGFromDocument(arg1:string,arg2:string):Promise<main.CompileSVGResult>;

export function EndEdit():Promise<void>;

export function ExportHTMLFromDocument(arg1:string,arg2:Array<string>,arg3:Array<visualapp.VariantPSRT>):Promise<string>;

export function ExportSVG(arg1:string):Promise<main.CompileSVGResult>;

export function ExportSVGFromDocument(arg1:string):Promise<main.CompileSVGResult>;

export function FormatDocumentJSON(arg1:string):Promise<string>;

export function FormatPageDocumentJSON(arg1:string,arg2:string):Promise<string>;

export function GetAssetDataURI(arg1:string):Promise<string>;

export function GetDocumentJSON():Promise<string>;

export function GetDocumentPSRT():Promise<string>;

export function GetState():Promise<visualapp.UIState>;

export function MergePageDocumentPSRT(arg1:string,arg2:string,arg3:string):Promise<string>;

export function MovePage(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function OpenFileDialog():Promise<visualapp.OpenFileResult>;

export function OpenImageFileDialog():Promise<string>;

export function ParseDocumentPSRT(arg1:string):Promise<string>;

export function PatchMask(arg1:string,arg2:number,arg3:visualapp.MaskPatch):Promise<void>;

export function PatchPage(arg1:visualapp.PagePatch):Promise<void>;

export function PatchText(arg1:string,arg2:number,arg3:visualapp.TextPatch):Promise<void>;

export function Redo():Promise<void>;

export function RefreshAssetURL(arg1:string):Promise<void>;

export function RefreshPageImage():Promise<void>;

export function RemoveConst(arg1:string):Promise<void>;

export function RemoveFont(arg1:string):Promise<void>;

export function RemovePage(arg1:string):Promise<void>;

export function RemoveText(arg1:number):Promise<void>;

export function RenderTextContentHTML(arg1:string):Promise<string>;

export function ReorderText(arg1:number,arg2:number,arg3:boolean):Promise<void>;

export function ReportClientError(arg1:string,arg2:string,arg3:string):Promise<void>;

export function Save():Promise<void>;

export function SaveAsDocumentJSON(arg1:string):Promise<string>;

export function SaveDocumentJSON(arg1:string):Promise<void>;

export function SelectText(arg1:number):Promise<void>;

export function SetActivePage(arg1:string):Promise<void>;

export function SetAutoCompile(arg1:boolean):Promise<void>;

export function SetDocumentFromPSRT(arg1:string):Promise<void>;

export function Undo():Promise<void>;
